### ISSUE TITLE
update to remoteStorage.js v0.7

### ISSUE THREAD

**Issue by michielbdejong** [shybyte/unhosted-time-tracker#4]
Hi @shybyte!
basically the same question as https://github.com/shared-stuff/shared-stuff.github.com/issues/2

I had a stab at it already (https://github.com/michielbdejong/unhosted-time-tracker/commits/master) but i got stuck where Angular tries to load null tasks, so I think it's best to ditch that branch and start from scratch.

sorry, at least i tried! :) let me know how i can help further with this, it would be very nice to add both unhosted-time-tracker and sharedstuff on https://unhosted.org/apps/

**Comment by shybyte** [comment]
I am currently travelling without a computer until 16. April.  I will update my apps to 0.7 when I'm back ASAP.

**Comment by michielbdejong** [comment]
great, enjoy your travels!

closing this issue in favor of https://github.com/shybyte/unhosted-time-tracker/pull/5
